### ISSUE TITLE
Modified sales_flat_quote table breaking extensions and abandoned carts across the board

### ISSUE THREAD

**Issue by andresinspace** [BoltApp/bolt-magento1#173]
### Preconditions
Magento 1.9x
Bolt Latest Community V1.2.0.1

### Steps to reproduce
Add to cart, go to cart, go to another page, go back to cart. Repeat.

### Expected result
The SAME quote should be updated when cart actions are triggered... there is NO reason to create a NEW quote, just UPDATE the existing quote...

### Actual result
New quotes are created with references to the 'old' quotes..
This causes the Abandoned Cart Reports to start showing duplicated carts abandoned..
sales_flat_quote and it's related tables now grow exponetially in size.. as new records are created for each visit to checkout/cart ... not good
3rd partymodules and other extensions that rely on sales_flat_quote are now all having duplicated records pulled in..
I got 8 abandoned cart emails from ONE cart, ONE site visit.. 

### GitHub Releases
Please limit releases to once a month.. having to update a module every week is not fun..

**Comment by andresinspace** [comment]
FYI, sales_flat_quote in a default magento 1 install is NEVER cleaned of ACTIVE quotes.. unless your magento module has been modified to clean them out.
This is going to cause peoples sites to slow way down on cart actions due to the table size growing indefinitely....

**Comment by daisy1754** [comment]
Thanks for insight! We have a plan to take some actions (eg., cleaning up old but active quotes). @mccottry can share details. 

Re: releases cycle, we tends to make patch version update with small tweaks. If you look at minor releases, 1.1.0 was in May and 1.2.0 was in July.

**Comment by daisy1754** [comment]
Creating copy is a design decision we've made and we cannot easily change it. We added cron to cleanup unused old quote in 1.3.0 hopefully it'll help.
