### ISSUE TITLE
Bolt breaking Shipping Estimator

### ISSUE THREAD

**Issue by andresinspace** [BoltApp/bolt-magento1#183]
### Preconditions
Magento 1.9x
Bolt Latest Community V1.2.0.1
### Steps to reproduce
Add Estimated Country/State/Zip (City is NOT required) for estimates..
Estimate
Select Estimate 
Update Totals

### Expected result
Should be added with proper price.

### Actual result
It adds the proper method, but the price is always $0

**Comment by andresinspace** [comment]
It appears the ‘multi-page’ checkout flag is being passed despite the checkout residing on checkout/cart index
(I think multi-page is confusing as a term here.. there is no other pages on this checkout process.. it is handled from start to finish entirely from the cart itself.)

    app\design\frontend\base\default\template\boltpay\replace.phtml line 147 calls getCartDataJs()
`<?=$this->getCartDataJs('multi-page'); ?>`

getCartDataJs is defined in boltpay.php 
    app\code\community\Bolt\Boltpay\Block\Checkout\Boltpay.php line 124 calls applyShippingRate()
  ```
  public function getCartDataJs($checkoutType = self::CHECKOUT_TYPE_MULTI_PAGE)
..///
if ($isMultiPage) {
                // Resets shipping rate
                $shippingMethod = $sessionQuote->getShippingAddress()->getShippingMethod();
                $boltHelper->applyShippingRate($sessionQuote, null); 
            }
```

**Comment by mccottry** [comment]
This is not reproducible in any of our environments.  I'm closing this task as a result.
