### ISSUE TITLE
Headers already sent 

### ISSUE THREAD

**Issue by AndresInSpace** [BoltApp/bolt-magento1#300]
### Preconditions
Magento 1.9x
Bolt Latest Community V1.3.8

### Issue 
The setHeader calls are assuming no other native or third-party modules have already set Headers on response. It does not overwrite the existing Content-type if a header is already set, resulting in errors when Bolt makes AJAX calls to prefetchEstimateAction in app/code/community/Bolt/Boltpay/controllers/ShippingController.php

PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0

Should be calling clearHeaders() as part of the method chain
`$this->getResponse()->clearHeaders()->setHeader('Content-type', 'application/json');`

**Comment by AndresInSpace** [comment]
PR https://github.com/BoltApp/bolt-magento1/pull/301

**Comment by mccottry** [comment]
@AndresInSpace This is a good point regarding 3rd party modules.  This is being handled in PR #301
