### ISSUE TITLE
Is it compatible with Magento enterprise?

### ISSUE THREAD

**Issue by webspeaks** [BoltApp/bolt-magento1#530]
Is it compatible with Magento enterprise?

**Comment by webspeaks** [comment]
I have installed it on Magento commerce 1.14.4.1 but during checkout it gives me following error:
`Invalid method Mage_SalesRule_Model_Validator::resetRoundingDeltas`
at line `httpdocs/app/code/community/Bolt/Boltpay/Helper/GeneralTrait.php(75)`.

I checked the code in `Mage_SalesRule_Model_Validator` but I could not find the function `resetRoundingDeltas()` in it. 
Can you please check how can we fix it?

**Comment by johnmccombs1** [comment]
@webspeaks We override class Mage_SalesRule_Model_Validator with class Bolt_Boltpay_Model_Validator to fix the rounding issue that occurs during the process of collecting the quote totals. In that class, we create a new method named resetRoundingDeltas. It looks like the message shows that Bolt doesn’t override class Mage_SalesRule_Model_Validator. Can you look into why it's not overriding this in your installation? See here https://github.com/BoltApp/bolt-magento1/blob/master/app/code/community/Bolt/Boltpay/Model/Validator.php

**Comment by adentong** [comment]
No update in almost 4 months. Closing.
